# Generated by Django 5.0.2 on 2024-03-11 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0007_order_products'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name': 'Order'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-name', 'price']},
        ),
    ]
